#!/bin/bash
#
# pagerduty-resolve is a wrapper around the PagerDuty API to close an incident
# from the command line.
#
# Copyright (c) 2012 Cold Brew Labs, Inc. See LICENSE for details.

# Uncomment and enter your service key here.
# PAGERDUTY_SERVICE_KEY="1234567890abcdef1234567890abcdef"

PAGERDUTY_PATHS="/usr/bin/pagerduty /usr/local/bin/pagerduty"

if [ -z "$1" ]; then
  echo "Usage: $0 <event>"
  exit 1
fi
if [ -z "$PAGERDUTY_SERVICE_KEY" ]; then
  echo "Failed to resolve event: you must set the PAGERDUTY_SERVICE_KEY variable."
  exit 1
fi

for binpath in $PAGERDUTY_PATHS; do
  if [ -x $binpath ]; then
    pagerduty_cmd=$binpath
    break
  fi
done

if [ -z $pagerduty_cmd ]; then
  echo "Could not trigger event: no pagerduty found in ${PAGERDUTY_PATHS}";
fi

EVENT=$1
HOST=`hostname -s`
INCIDENT_KEY=`echo "$HOST:$EVENT" | md5sum | cut -f 1 -d ' '`
TMP_FILE="/tmp/pagerduty-$INCIDENT_KEY"

DESCRIPTION="$EVENT resolved on $HOST"

rm -f $TMP_FILE
$pagerduty_cmd -k "$PAGERDUTY_SERVICE_KEY" -i "$INCIDENT_KEY" --description="$DESCRIPTION" resolve

if [ "$?" -ne "0" ]; then
  echo "Failed to resolve incident"
  exit 1
fi

echo "Incident resolved successfully"
exit 0
